/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzaguiplan;

import java.awt.Dimension;
import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;

/**
 *
 * @author lee_c
 */
public class OrderGUI extends javax.swing.JFrame {

    /**
     * Creates new form OrderGUI
     */
    public OrderGUI() {
        initComponents();//everything on screen is built here
        //add your code here
        this.redRadio.setSelected(true);

        this.pizzaList.setModel(pizzaListModel);
        this.updateButton.setVisible(false);
        this.removeButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sizeGroup = new javax.swing.ButtonGroup();
        sauceGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        smallRadio = new javax.swing.JRadioButton();
        mediumRadio = new javax.swing.JRadioButton();
        largeRadio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        redRadio = new javax.swing.JRadioButton();
        whiteRadio = new javax.swing.JRadioButton();
        bbqRadio = new javax.swing.JRadioButton();
        toppingPanel = new javax.swing.JPanel();
        excheeseCheck = new javax.swing.JCheckBox();
        pepperoniCheck = new javax.swing.JCheckBox();
        mushroomCheck = new javax.swing.JCheckBox();
        grPepCheck = new javax.swing.JCheckBox();
        sausageCheck = new javax.swing.JCheckBox();
        hamCheck = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        totalPriceLabel = new javax.swing.JLabel();
        orderButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pizzaList = new javax.swing.JList<>();
        prebuiltCombo = new javax.swing.JComboBox<>();
        updateButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ravie", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Luigi's Pizza");

        sizeGroup.add(smallRadio);
        smallRadio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        smallRadio.setText("Small");
        smallRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallRadioActionPerformed(evt);
            }
        });

        sizeGroup.add(mediumRadio);
        mediumRadio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mediumRadio.setText("Medium");
        mediumRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumRadioActionPerformed(evt);
            }
        });

        sizeGroup.add(largeRadio);
        largeRadio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        largeRadio.setSelected(true);
        largeRadio.setText("Large");
        largeRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeRadioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Pick a size");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Pick a sauce");

        sauceGroup.add(redRadio);
        redRadio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        redRadio.setText("Red Sauce");
        redRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redRadioActionPerformed(evt);
            }
        });

        sauceGroup.add(whiteRadio);
        whiteRadio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        whiteRadio.setText("White Sauce");
        whiteRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteRadioActionPerformed(evt);
            }
        });

        sauceGroup.add(bbqRadio);
        bbqRadio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bbqRadio.setText("BBQ Sauce");
        bbqRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbqRadioActionPerformed(evt);
            }
        });

        toppingPanel.setLayout(new java.awt.GridLayout(3, 2));

        excheeseCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        excheeseCheck.setText("Extra Cheese");
        excheeseCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excheeseCheckActionPerformed(evt);
            }
        });
        toppingPanel.add(excheeseCheck);

        pepperoniCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pepperoniCheck.setText("Pepperoni");
        pepperoniCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepperoniCheckActionPerformed(evt);
            }
        });
        toppingPanel.add(pepperoniCheck);

        mushroomCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mushroomCheck.setText("Mushroom");
        mushroomCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mushroomCheckActionPerformed(evt);
            }
        });
        toppingPanel.add(mushroomCheck);

        grPepCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        grPepCheck.setText("Green Peppers");
        grPepCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grPepCheckActionPerformed(evt);
            }
        });
        toppingPanel.add(grPepCheck);

        sausageCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sausageCheck.setText("Sausage");
        sausageCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sausageCheckActionPerformed(evt);
            }
        });
        toppingPanel.add(sausageCheck);

        hamCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hamCheck.setText("Ham");
        hamCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamCheckActionPerformed(evt);
            }
        });
        toppingPanel.add(hamCheck);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Toppings");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Current Pizza Price");

        priceLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        priceLabel.setText("$0.00");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Total Order Price");

        totalPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totalPriceLabel.setText("$0.00");

        orderButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        orderButton.setText("Add to Order");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        pizzaList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pizzaList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                pizzaListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(pizzaList);

        prebuiltCombo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prebuiltCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prebuilt Pizza", "Meat Lovers", "Veggie Lovers", "Supreme" }));
        prebuiltCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prebuiltComboActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        removeButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(smallRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mediumRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(largeRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(whiteRadio)
                                    .addComponent(redRadio)
                                    .addComponent(bbqRadio))
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(priceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                            .addComponent(totalPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(orderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 8, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(toppingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(prebuiltCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(priceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smallRadio)
                    .addComponent(redRadio)
                    .addComponent(jLabel6)
                    .addComponent(totalPriceLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mediumRadio)
                        .addComponent(whiteRadio)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(largeRadio)
                            .addComponent(bbqRadio)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeButton)
                            .addComponent(updateButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toppingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(prebuiltCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void clearToppings() {
        this.excheeseCheck.setSelected(false);
        this.grPepCheck.setSelected(false);
        this.hamCheck.setSelected(false);
        this.mushroomCheck.setSelected(false);
        this.pepperoniCheck.setSelected(false);
        this.sausageCheck.setSelected(false);
    }

    private void prebuiltComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prebuiltComboActionPerformed
        // TODO add your handling code here:
        int choice = this.prebuiltCombo.getSelectedIndex();
        clearToppings();
        switch (choice) {
            case 1:
                //meat lovers   
                this.hamCheck.setSelected(true);
                this.pepperoniCheck.setSelected(true);
                this.sausageCheck.setSelected(true);
                break;
            case 2:
                //veggie lovers
                this.grPepCheck.setSelected(true);
                this.mushroomCheck.setSelected(true);
                break;
            case 3:
                //everything         
                this.excheeseCheck.setSelected(true);
                this.grPepCheck.setSelected(true);
                this.hamCheck.setSelected(true);
                this.mushroomCheck.setSelected(true);
                this.pepperoniCheck.setSelected(true);
                this.sausageCheck.setSelected(true);
                break;
            case 0:
            default:
            //deselect everything chosen
        }
        priceThePizza();
    }//GEN-LAST:event_prebuiltComboActionPerformed

    private void smallRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallRadioActionPerformed
        // TODO add your handling code here:
        size = "small";
        priceThePizza();
    }//GEN-LAST:event_smallRadioActionPerformed

    private void mediumRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumRadioActionPerformed
        // TODO add your handling code here:
        size = "medium";
        priceThePizza();
    }//GEN-LAST:event_mediumRadioActionPerformed

    private void largeRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeRadioActionPerformed
        // TODO add your handling code here:
        size = "large";
        priceThePizza();
    }//GEN-LAST:event_largeRadioActionPerformed

    private void redRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redRadioActionPerformed
        // TODO add your handling code here:
        sauce = "red sauce";
        priceThePizza();
    }//GEN-LAST:event_redRadioActionPerformed

    private void whiteRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteRadioActionPerformed
        // TODO add your handling code here:
        sauce = "white sauce";
        priceThePizza();
    }//GEN-LAST:event_whiteRadioActionPerformed

    private void bbqRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbqRadioActionPerformed
        // TODO add your handling code here:
        sauce = "bbq sauce";
        priceThePizza();
    }//GEN-LAST:event_bbqRadioActionPerformed

    private void excheeseCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excheeseCheckActionPerformed
        // TODO add your handling code here:
        priceThePizza();
    }//GEN-LAST:event_excheeseCheckActionPerformed

    private void pepperoniCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepperoniCheckActionPerformed
        // TODO add your handling code here:
        priceThePizza();
    }//GEN-LAST:event_pepperoniCheckActionPerformed

    private void mushroomCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mushroomCheckActionPerformed
        // TODO add your handling code here:
        priceThePizza();
    }//GEN-LAST:event_mushroomCheckActionPerformed

    private void grPepCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grPepCheckActionPerformed
        // TODO add your handling code here:
        priceThePizza();
    }//GEN-LAST:event_grPepCheckActionPerformed

    private void sausageCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sausageCheckActionPerformed
        // TODO add your handling code here:
        priceThePizza();
    }//GEN-LAST:event_sausageCheckActionPerformed

    private void hamCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamCheckActionPerformed
        // TODO add your handling code here:
        priceThePizza();
    }//GEN-LAST:event_hamCheckActionPerformed

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        // TODO add your handling code here:
        pizzaListModel.addElement(currentPizza);
        //totalCost += currentPizza.getPrice();
       // this.totalPriceLabel.setText("$" + totalCost);
       calcTotalOrder();

    }//GEN-LAST:event_orderButtonActionPerformed

    private void pizzaListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_pizzaListValueChanged
        // TODO add your handling code here:
        selectedPizza = pizzaList.getSelectedValue();
        pizzaNum = pizzaList.getSelectedIndex();

        //set the options on the screen
        if (selectedPizza.getSize().startsWith("s")) {
            this.smallRadio.setSelected(true);
        } else if (selectedPizza.getSize().startsWith("m")) {
            this.mediumRadio.setSelected(true);
        } else if (selectedPizza.getSize().startsWith("l")) {
            this.largeRadio.setSelected(true);
        }

        //repeat for sauce
        this.excheeseCheck.setSelected(selectedPizza.isExcheese());
        this.grPepCheck.setSelected(selectedPizza.isGreenpepper());
        this.hamCheck.setSelected(selectedPizza.isHam());
        this.mushroomCheck.setSelected(selectedPizza.isMushroom());
        this.pepperoniCheck.setSelected(selectedPizza.isPepperoni());
        this.sausageCheck.setSelected(selectedPizza.isSausage());
        priceThePizza();
        this.updateButton.setVisible(true);
        this.removeButton.setVisible(true);
        
    }//GEN-LAST:event_pizzaListValueChanged

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        //move the selectedNumber to the variables section
        pizzaListModel.setElementAt(currentPizza, pizzaNum);
        this.updateButton.setVisible(false);
        this.removeButton.setVisible(false);
        calcTotalOrder();
       
    }//GEN-LAST:event_updateButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        pizzaListModel.remove(pizzaNum);
        this.updateButton.setVisible(false);
        this.removeButton.setVisible(false);
        //bug - have to drag screen to redraw it??
        calcTotalOrder();
         
    }//GEN-LAST:event_removeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bbqRadio;
    private javax.swing.JCheckBox excheeseCheck;
    private javax.swing.JCheckBox grPepCheck;
    private javax.swing.JCheckBox hamCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton largeRadio;
    private javax.swing.JRadioButton mediumRadio;
    private javax.swing.JCheckBox mushroomCheck;
    private javax.swing.JButton orderButton;
    private javax.swing.JCheckBox pepperoniCheck;
    private javax.swing.JList<Pizza> pizzaList;
    private javax.swing.JComboBox<String> prebuiltCombo;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JRadioButton redRadio;
    private javax.swing.JButton removeButton;
    private javax.swing.ButtonGroup sauceGroup;
    private javax.swing.JCheckBox sausageCheck;
    private javax.swing.ButtonGroup sizeGroup;
    private javax.swing.JRadioButton smallRadio;
    private javax.swing.JPanel toppingPanel;
    private javax.swing.JLabel totalPriceLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JRadioButton whiteRadio;
    // End of variables declaration//GEN-END:variables
    //custom variables
    private double totalCost = 0;
    private Pizza currentPizza;
    private String size = "large";
    private String sauce = "red";
    private DefaultListModel<Pizza> pizzaListModel
            = new DefaultListModel<Pizza>();
    Pizza selectedPizza;
    int pizzaNum;

    public void priceThePizza() {
        currentPizza = new Pizza(size, sauce, this.excheeseCheck.isSelected(),
                this.grPepCheck.isSelected(), this.hamCheck.isSelected(),
                this.mushroomCheck.isSelected(), this.pepperoniCheck.isSelected(),
                this.sausageCheck.isSelected());
        this.priceLabel.setText("$" + currentPizza.getPrice());
    }
    
    public void calcTotalOrder(){
        totalCost = 0;
        for(int p=0; p < pizzaListModel.getSize(); p++){
            totalCost += pizzaListModel.elementAt(p).getPrice();
        }
        
        this.totalPriceLabel.setText("$" + totalCost);
    }
}
