/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moviemonsterplan;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author lee_c
 */
public class MovieMonsterGUI extends javax.swing.JFrame {

    private Toolkit tools;  //provides access to the file system and other aspects of Java
    //allows adjustments to the image
    Image blankImage, halloweenImage, alienImage, fridayImage;
    AudioStream halloweenStream, fridayStream, alienStream;

    AudioStream playingStream;

    private void loadAssets() {
        InputStream in;
        blankImage = tools.getImage(getClass().getResource("blank.png"));
        halloweenImage = tools.getImage(getClass().getResource("halloweenPoster.jpg"));
        alienImage = tools.getImage(getClass().getResource("alienPoster.jpg"));
        fridayImage = tools.getImage(getClass().getResource("friday13thPoster.jpg"));

        in = getClass().getResourceAsStream("halloween.wav");
        try {
            halloweenStream = new AudioStream(in);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Halloween sound failed");
            System.exit(2);
        }

        in = getClass().getResourceAsStream("alien.wav");
        try {
            alienStream = new AudioStream(in);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Alien sound failed");
            System.exit(2);
        }

        in = getClass().getResourceAsStream("friday13th.wav");
        try {
            fridayStream = new AudioStream(in);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Friday sound failed");
            System.exit(2);
        }
    }

    /**
     * Creates new form MovieMonsterGUI
     */
    public MovieMonsterGUI() {
        initComponents();
        tools = Toolkit.getDefaultToolkit();    //tools can access the file system
        //loads the file from the package, 
        //if you added a package or folder, add it like resources//reel.jpg
        this.setIconImage(tools.getImage(getClass().getResource("reel.jpg")));
        this.setTitle("Movie Monster");
        loadAssets();
        showImage(blankImage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        alienButton = new javax.swing.JButton();
        halloweenButton = new javax.swing.JButton();
        fridayButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        alienButton.setText("Alien");
        alienButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alienButtonActionPerformed(evt);
            }
        });

        halloweenButton.setText("Halloween");
        halloweenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halloweenButtonActionPerformed(evt);
            }
        });

        fridayButton.setText("Friday 13th");
        fridayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fridayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fridayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alienButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(halloweenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(alienButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(halloweenButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fridayButton)))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void halloweenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halloweenButtonActionPerformed
        // TODO add your handling code here:
        showImage(halloweenImage);
        playSound(halloweenStream);
    }//GEN-LAST:event_halloweenButtonActionPerformed

    private void alienButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alienButtonActionPerformed
        // TODO add your handling code here:
        showImage(alienImage);
        playSound(alienStream);
    }//GEN-LAST:event_alienButtonActionPerformed

    private void fridayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fridayButtonActionPerformed
        // TODO add your handling code here:
        showImage(fridayImage);
        playSound(fridayStream);
    }//GEN-LAST:event_fridayButtonActionPerformed
private void playSound(AudioStream theStream){
        //demo without the stop
        AudioPlayer.player.stop(playingStream);
        playingStream = theStream;
        AudioPlayer.player.start(playingStream);
    }
     private void showImage(Image theImage){
       
        Image scaledMonster = theImage.getScaledInstance(imageLabel.getWidth(),
                imageLabel.getHeight(), Image.SCALE_SMOOTH);
        this.imageLabel.setIcon(new ImageIcon(scaledMonster));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieMonsterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieMonsterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieMonsterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieMonsterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieMonsterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alienButton;
    private javax.swing.JButton fridayButton;
    private javax.swing.JButton halloweenButton;
    private javax.swing.JLabel imageLabel;
    // End of variables declaration//GEN-END:variables
}
