/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicsplan;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author lee_c
 */
public class CityscapePlan extends javax.swing.JFrame {

    /**
     * Creates new form CityscapePlan
     */
    int width = 1024;
    int height = 600;
    Toolkit tools = Toolkit.getDefaultToolkit();
    Image superman = tools.getImage(this.getClass().getResource("super.gif"));

    public CityscapePlan() {
        initComponents();
        this.setSize(width, height);

    }

    public void randomBuildings(Graphics g) {
        int startX, startY, wid, hei, red, green, blue;
        int win, winX, winY, numWin;
        
        for (int x = 0; x < 15; x++) {
            startX = (int) (Math.random() * (width - 100));
            startY = (int) (200 + Math.random() * 300);
            wid = (int) (60 + Math.random() * 200);
            hei = height - startY;

            red = (int) (Math.random() * 255);
            green = (int) (Math.random() * 255);
            blue = (int) (Math.random() * 255);
            g.setColor(new Color(red, green, blue));
            g.fillRect(startX, startY, wid, hei);

            g.setColor(Color.BLACK);
            g.drawRect(startX, startY, wid, hei);
            
            win = wid / 6;
            //winY = startY + win / 2;
            numWin = hei / win;
            winY = 0;
            for (double across = .5; across <= 4.5; across += 2) {
                winX = startX + (int) (across * win);
                for (int down = 1; down < numWin; down += 2) {
                    winY = startY + down * win;
                    g.fillRect(winX, winY, win, win);
                }
            }
        }
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        g.setColor(Color.cyan);
        g.fillRect(0, 0, width, height);

        //draw sun
        g.setColor(Color.yellow);
        g.fillOval(700, 45, 80, 80);

        //draw a string
        g.setColor(new Color(255, 0, 100));
        g.setFont(new Font("Arial", Font.BOLD, 24));
        g.drawString("Click to redraw, right click to quit", 220, 100);

        //draw some blue buildings
//        g.setColor(Color.BLUE);
//        g.fillRect(0, 400, 55, (height - 400));
//        g.fillRect(300, 250, 80, (height - 250));
//        g.fillRect(500, 300, 50, (height - 300));
//        g.fillRect(750, 450, 50, (height - 150));
//        g.fillRect(600, 150, 75, (height - 150));
        //add superman
        g.drawImage(superman, 50, 50, 98, 48, this);

        //random buildings
        randomBuildings(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(this, evt.getButton() + " clicked");
        int button = evt.getButton();
        if (button == evt.BUTTON1) {
            repaint();
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CityscapePlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CityscapePlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CityscapePlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CityscapePlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CityscapePlan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
