/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guireadwrite;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.file.FileSystem;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author lee_c
 */
public class CompanyGUI extends javax.swing.JFrame {

    FileSystem fs;
    Path pathToFile;
    InputStream companyIn = null;
    BufferedReader companyReader;
    ArrayList<Company> contactList = new ArrayList<Company>();
    int index = 0;  //location in the list
    
    public void showRecord(){
        this.idSpinner.setValue(contactList.get(index).getId());
        this.fnameField.setText(contactList.get(index).getFname());
        this.lnameField.setText(contactList.get(index).getLname());
        this.emailField.setText(contactList.get(index).getEmail());
        this.companyField.setText(contactList.get(index).getCompany());
        this.setTitle("Record # " + index);
    }

    public void updateRecord(){
        //call this before moving a record
        contactList.get(index).setFname(this.fnameField.getText());
        contactList.get(index).setLname(this.lnameField.getText());
        contactList.get(index).setEmail(this.emailField.getText());
        contactList.get(index).setCompany(this.companyField.getText());
        contactList.get(index).setId((int) this.idSpinner.getValue());
        
    }
    
    public void writeToFile(){
        //call when the form closes
        //"c:\\data\\company.csv
        String fileName = "c:\\data\\company.csv";
        String outputLine;
        File file = new File(fileName);
            
        try {
            
            FileWriter fileOut = new FileWriter(file);
            for(int x=0; x < contactList.size(); x++){
                outputLine = String.format("%d,%s,%s,%s,%s\n", contactList.get(x).getId(),
                      contactList.get(x).getFname(),
                      contactList.get(x).getLname(),
                      contactList.get(x).getCompany(),
                      contactList.get(x).getEmail());
                fileOut.write(outputLine);
            }
            fileOut.flush();
            fileOut.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,"Cannot write country file", "File IO Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
    }
    /**
     * tools.getImage(getClass().getResource("blank.png")); Creates new form
     * CompanyGUI
     */
    public CompanyGUI() {
        initComponents();
        fs = FileSystems.getDefault();//allows access to disk
        pathToFile = fs.getPath("c:\\data\\company.csv");
        Company aPerson;
        String line;

        try {
            companyIn = Files.newInputStream(pathToFile);
            companyReader = new BufferedReader(new InputStreamReader(companyIn));
            
            while((line = companyReader.readLine()) != null){
                String records[] = line.split(",");
                //id, fname, lname, company, email
                aPerson = new Company();
                
                try {
                    aPerson.setId(Integer.parseInt(records[0]));
                    aPerson.setFname(records[1]);
                    aPerson.setLname(records[2]);
                    aPerson.setCompany(records[3]);
                    aPerson.setEmail(records[4]);
                    contactList.add(aPerson);
                } catch (Exception numberFormatException) {
                    //do nothing on error - bad records not added to list
                    //eliminates problems with missing fields and bad ID numbers
                    //in reality you need to fix the bad records
                }            
            }
            //JOptionPane.showMessageDialog(this, "Records read = " + contactList.size());
            showRecord();
            companyIn.close();
        }//end of try
        catch (IOException ex) {
            System.out.println("Cannot open " + pathToFile.getFileName());
            System.exit(1);
        }//end of catch

    }//end of constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        fnameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lnameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        companyField = new javax.swing.JTextField();
        firstButton = new javax.swing.JButton();
        prevButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        lastButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Record # ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        dataPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        dataPanel.setMinimumSize(new java.awt.Dimension(400, 400));
        dataPanel.setPreferredSize(new java.awt.Dimension(400, 400));
        dataPanel.setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setText("ID Number");
        dataPanel.add(jLabel1);
        dataPanel.add(idSpinner);

        jLabel2.setText("First Name");
        dataPanel.add(jLabel2);

        fnameField.setText("jTextField1");
        dataPanel.add(fnameField);

        jLabel3.setText("Last Name");
        dataPanel.add(jLabel3);

        lnameField.setText("jTextField2");
        dataPanel.add(lnameField);

        jLabel4.setText("Email");
        dataPanel.add(jLabel4);

        emailField.setText("jTextField3");
        dataPanel.add(emailField);

        jLabel5.setText("Company");
        dataPanel.add(jLabel5);

        companyField.setText("jTextField4");
        dataPanel.add(companyField);

        firstButton.setText("|<");
        firstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstButtonActionPerformed(evt);
            }
        });

        prevButton.setText("<");
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });

        nextButton.setText(">");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        lastButton.setText(">|");
        lastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastButtonActionPerformed(evt);
            }
        });

        newButton.setText("*");

        deleteButton.setForeground(new java.awt.Color(255, 51, 51));
        deleteButton.setText("X");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(firstButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prevButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(newButton)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nextButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lastButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(deleteButton)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstButton)
                    .addComponent(prevButton)
                    .addComponent(nextButton)
                    .addComponent(lastButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newButton)
                    .addComponent(deleteButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        updateRecord();
        if(index < contactList.size() -1){
            index ++;
            showRecord();
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtonActionPerformed
        // TODO add your handling code here:
        updateRecord();
         if(index > 0){
            index --;
            showRecord();
        }
    }//GEN-LAST:event_prevButtonActionPerformed

    private void firstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstButtonActionPerformed
        // TODO add your handling code here:
        updateRecord();
        index = 0;
        showRecord();
    }//GEN-LAST:event_firstButtonActionPerformed

    private void lastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastButtonActionPerformed
        // TODO add your handling code here:
        index = contactList.size() -1;
        showRecord();
    }//GEN-LAST:event_lastButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
         updateRecord();
        writeToFile();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompanyGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompanyGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompanyGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompanyGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompanyGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField companyField;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton firstButton;
    private javax.swing.JTextField fnameField;
    private javax.swing.JSpinner idSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton lastButton;
    private javax.swing.JTextField lnameField;
    private javax.swing.JButton newButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton prevButton;
    // End of variables declaration//GEN-END:variables
}
